# Generated by Django 6.0 on 2025-12-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_supplier_rename_cost_price_product_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
