# Generated by Django 6.0 on 2025-12-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
